name: build
on:
  push:
    paths: 
      - '**.js'
jobs:
  build:
    name: my  build job
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        node-version: [12.x, 14.x, 16.x]
        exclude:
          - os: macos-latest
            node-version: 12.x
          - os: ubuntu-latest
            node-version: 12.x
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }} 
    - run: npm ci 
    - run: npm run build --if-present
